theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "custom"
command = "~/.config/i3/cmus_playing_status.sh"
interval = 2

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d %b, %R"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{average}°"

#[[block]]
#block = "nvidia_gpu"
#label = "GTX 960M"
#show_memory = false
#show_clocks = false
#interval = 5

[[block]]
block = "net"
device = "wlp5s0"
ssid = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
