theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "pomodoro"
length = 45
break_length = 5
message = "Break!"
break_message = "Work!"
use_nag = true
nag_path = "i3-nagbar"

[[block]]
block = "custom"
command = "echo `~/.config/i3/cmus_playing_status.sh`"
interval = 2

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d %b, %R"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{average}°"

#[[block]]
#block = "bluetooth"
#mac = "00:00:00:01:9F:EE"

[[block]]
block = "memory"
format_mem = "{mem_used;G}/{mem_total;G}({mem_used_percents:1})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "nvidia_gpu"
label = "GTX 960M"
show_memory = false
show_clocks = false
interval = 5

#[[block]]
#block = "net"
#device = "wlp5s0"
##ssid = true
#interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
